### ISSUE TITLE
[BUG] AutoReset not enabled for MuJoCo envs

### ISSUE THREAD

**Issue by dtch1997** [PKU-Alignment/omnisafe#268]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### What version of OmniSafe are you using?

0.5.1.dev11+g7432fc2

### System information

3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] linux
0.5.1.dev11+g7432fc2

### Problem description

AutoReset not enabled for MuJoCo envs resulting in crash when learning agent. 

### Reproducible example code

The Python snippets:

```python

```

Command lines:

```bash
python examples/train_policy --env-id Hopper-v4
```

Extra dependencies:

```text

```

Steps to reproduce:

1.
2.
3.

### Traceback

```pytb
Traceback (most recent call last):
  File "/home/daniel/Documents/github/rl_cbf/rl_cbf/safe_rl/train_policy.py", line 91, in <module>
    agent.learn()
  File "/home/daniel/Documents/github/rl_cbf/.venv/lib/python3.10/site-packages/omnisafe/algorithms/algo_wrapper.py", line 172, in learn
    ep_ret, ep_cost, ep_len = self.agent.learn()
  File "/home/daniel/Documents/github/rl_cbf/.venv/lib/python3.10/site-packages/omnisafe/algorithms/on_policy/base/policy_gradient.py", line 246, in learn
    self._env.rollout(
  File "/home/daniel/Documents/github/rl_cbf/.venv/lib/python3.10/site-packages/omnisafe/adapter/onpolicy_adapter.py", line 118, in rollout
    info['final_observation'][idx],
KeyError: 'final_observation'
```

### Expected behavior

Training works with MuJoCo envs.

**Comment by Gaiejj** [comment]
After carefully reviewing of `omnisafe/envs/mujoco_env.py` file, I approve with your opinion and I think setting ``need_auto_reset_wrapper = True`` is critical to solve that problem. Thanks to your pull request in #269.
